---
title: "Mbita Kenya Ab study, simulated cutoffs"
output:
  html_notebook:
    highlight: haddock
    theme: default
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: yes
      smooth_scroll: yes
---


# Preamble
```{r preamble}
library(here)
here()

library(tidyverse)
library(mgcv)
library(foreach)
library(gridExtra)

# grab some colors for plotting
ggplotcols <- scales::hue_pal()(3)
# bright color blind palette:  https://personal.sron.nl/~pault/ 
cblack <- "#000004FF"
cblue <- "#3366AA"
cteal <- "#11AA99"
cgreen <- "#66AA55"
cchartr <- "#CCCC55"
cmagent <- "#992288"
cred <- "#EE3333"
corange <- "#EEA722"
cyellow <- "#FFEE33"
cgrey <- "#777777"

pcols <- c(ggplotcols,cmagent,corange)

```

# Load coastal Kenya measurements
Load AsHb measurements and filter 

```{r load data, warning=FALSE}
d <- readRDS(here("data","mbita_psac.rds"))

# reshape to long format
dl <- d %>%
  select(year,community=vid,age=agey,msp1,sea,nie,ashb,vsp5) %>%
  gather(key=antigen,value=mfi,-year,-community,-age) %>%
  mutate(antigen = factor(antigen,levels=c("sea","nie","ashb","msp1","vsp5"))) %>%
  group_by(year,community,antigen) %>%
  arrange(year,community,antigen,age)

dl <- dl %>%
  mutate(logmfi = ifelse(mfi>0,log10(mfi),log10(1)))

# add ROC-based cutoffs
dl$roccut <- NA
dl$roccut[dl$antigen %in% "msp1"] <- log10(170)
dl$roccut[dl$antigen %in% "sea"] <- log10(965)
dl$roccut[dl$antigen %in% "ashb"] <- log10(418)
dl$roccut[dl$antigen %in% "nie"] <- log10(659)
dl$roccut[dl$antigen %in% "vsp5"] <- log10(281)


# define seroprevalence based on ROC cutoffs
dl <- dl %>%
  mutate(seropos = ifelse(logmfi>roccut,1,0))

# create formatted antigen labels
dl <- dl %>%
  mutate(antigenf=factor(antigen,levels=c("sea","nie","ashb","msp1","vsp5"),
                         labels=c("S. mansoni SEA",
                                  "S. stercoralis NIE",
                                  "Ascaris spp. AsHb",
                                  "P. falciparum MSP-1",
                                  "Giardia spp. VSP-5")))

```


# Community seroprevalence vs mean, across cutoffs

```{r cluster means}

# create seropositivity indicators across a range of cutoff values
cuts <- seq(2,4,by=0.25)
posM <- foreach(i=1:length(cuts),.combine=cbind) %do% {
  ifelse(dl$logmfi>cuts[i],1,0)
}
posM <- data.frame(posM)
colnames(posM) <- paste("cut",1:length(cuts),sep="")
posM <- posM %>%
  mutate(community=dl$community,antigenf=dl$antigenf,logmfi=dl$logmfi)

dlc <- posM %>%
  group_by(community,antigenf) %>%
  summarize_all(mean) %>% 
  gather(cutoff,seroprev,-community,-antigenf,-logmfi) %>%
  arrange(antigenf,community) %>%
  ungroup() %>%
  mutate(cutoff=factor(cutoff,levels=paste("cut",1:length(cuts),sep=""),labels=cuts),
         cutval=rep(cuts,length(unique(dl$community))*length(unique(dl$antigen))))


```


```{r prev vs mfi figure,fig.width=5,fig.height=5}

cutd <- data.frame(antigen=rep(levels(dl$antigenf),rep(length(cuts),length(levels(dl$antigenf)))) ,
                   x0=rep(cuts,length(unique(dl$antigenf))),
                   y0=0,y1=1) %>%
  mutate(cutoff=factor(x0))


pcutsdist <- ggplot(data=dl) +
  facet_wrap(~antigenf,ncol=1, scales="free_x") +
  geom_segment(data=cutd,aes(x=x0,xend=x0,y=y0,yend=y1,color=cutoff),lty=1,lwd=0.5,alpha=0.7) +
  geom_density(aes(x=logmfi),alpha=0.2,color=NA,fill="black") +
  scale_color_hue(h.start=270)+
  labs(x="log10 luminex response (MFI-bg)",y="density") +
  coord_cartesian(xlim=c(0,4.5))+
  theme_minimal() + 
  theme(legend.position="left",
        strip.text.y=element_text(angle=0))


pmfivprev <- ggplot(data=dlc,aes(x=logmfi,y=seroprev,group=cutoff,color=cutoff)) +
  facet_wrap(~antigenf,ncol=1,scales="free_x") +
  geom_point(alpha=0.7,size=0.1) +
  geom_smooth(,method="loess",lwd=0.25,se=FALSE) +
  scale_y_continuous(breaks=seq(0,1,by=0.2),labels=seq(0,100,by=20))+
  scale_color_hue(h.start=270)+
  # scale_color_gradient(low=cteal,high=cblue)+
  coord_cartesian(ylim=c(0,1)) +
  labs(x="community mean log10 MFI",y="community seroprevalence (%)") +
  theme_minimal() +
  theme(legend.position="none")

p2panel <- grid.arrange(pcutsdist,pmfivprev,nrow=1,ncol=2,widths=c(1,0.7))

# save png file for presentation
ggsave(filename=here("output","mbita-cutoffsens-vertical.png"),plot=p2panel,device="png",width=5.5,height=9)

```




## Alternate figure layout 
(horizontal orientation for presentation)

```{r prev vs mfi figure 2}

pcutsdist2 <- ggplot(data=dl) +
  facet_wrap(~antigenf,nrow=1) +
  geom_segment(data=cutd,aes(x=x0,xend=x0,y=y0,yend=y1,color=cutoff),lty=1,lwd=0.25) +
  geom_density(aes(x=logmfi),alpha=0.2,color=NA,fill="black") +
  labs(x="log10 luminex response (MFI-bg)",y="density") +
  scale_color_hue(h.start=270)+
  guides(color=guide_legend(title="cutoff",nrow=1))+
  theme_minimal() + 
  theme(legend.position="top",
        strip.text.y=element_text(angle=0))


pmfivprev2 <- ggplot(data=dlc,aes(x=logmfi,y=seroprev,group=cutoff,color=cutoff)) +
  facet_wrap(~antigenf,nrow=1,scales="free_x") +
  geom_point(alpha=0.7,size=0.1) +
  geom_smooth(,method="loess",lwd=0.25,se=FALSE) +
  scale_y_continuous(breaks=seq(0,1,by=0.2),labels=seq(0,100,by=20))+
  scale_color_hue(h.start=270)+
  coord_cartesian(ylim=c(0,1)) +
  labs(x="community mean log10 MFI",y="community seroprevalence (%)") +
  theme_minimal() +
  theme(legend.position="none")


p2panel <- grid.arrange(pcutsdist2,pmfivprev2,nrow=2,ncol=1)

# save png file for presentation
ggsave(filename=here("output","mbita-cutoffsens.png"),plot=p2panel,device="png",width=7,height=5)
```

